airtable:
  base: appwdmCZrCmknlpbc
  concepts:
    view: List
    fields:
      - name
      - description
      - bg
      - _parent
      - _children
      - _related
      - media

quiz:
  HINT_SCORE: 0.5
  QUESTION_COUNT: 10
  ANSWER_COUNT: 4
  VALIDATION_TIME: 3
  levels:
    - easy
    - medium
    - hard
  topics:
    - flora_fauna
    - medi_fisic
